// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
)

type ShortenLink struct {
	ID          interface{}
	ShortCode   string
	OriginalUrl string
	CreatedAt   sql.NullTime
	Views       sql.NullInt64
}
