// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"
	"database/sql"
)

const createShortenLink = `-- name: CreateShortenLink :one
INSERT INTO SHORTEN_LINKS
(short_code, original_url)
VALUES(
    ?, ?
)
RETURNING id, short_code, original_url, created_at, views
`

type CreateShortenLinkParams struct {
	ShortCode   string
	OriginalUrl string
}

func (q *Queries) CreateShortenLink(ctx context.Context, arg CreateShortenLinkParams) (ShortenLink, error) {
	row := q.db.QueryRowContext(ctx, createShortenLink, arg.ShortCode, arg.OriginalUrl)
	var i ShortenLink
	err := row.Scan(
		&i.ID,
		&i.ShortCode,
		&i.OriginalUrl,
		&i.CreatedAt,
		&i.Views,
	)
	return i, err
}

const getShortenLink = `-- name: GetShortenLink :one
SELECT
id, original_url, created_at, views
FROM SHORTEN_LINKS
WHERE short_code = ?
LIMIT 1
`

type GetShortenLinkRow struct {
	ID          interface{}
	OriginalUrl string
	CreatedAt   sql.NullTime
	Views       sql.NullInt64
}

func (q *Queries) GetShortenLink(ctx context.Context, shortCode string) (GetShortenLinkRow, error) {
	row := q.db.QueryRowContext(ctx, getShortenLink, shortCode)
	var i GetShortenLinkRow
	err := row.Scan(
		&i.ID,
		&i.OriginalUrl,
		&i.CreatedAt,
		&i.Views,
	)
	return i, err
}

const incrementViews = `-- name: IncrementViews :exec
UPDATE shorten_links
SET views = views + 1
WHERE short_code = ?
`

func (q *Queries) IncrementViews(ctx context.Context, shortCode string) error {
	_, err := q.db.ExecContext(ctx, incrementViews, shortCode)
	return err
}
