// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"
)

const createShortenLink = `-- name: CreateShortenLink :one
INSERT INTO SHORTEN_LINKS
(short_code, original_url)
VALUES(
    ?, ?
)
RETURNING id
`

type CreateShortenLinkParams struct {
	ShortCode   string
	OriginalUrl string
}

func (q *Queries) CreateShortenLink(ctx context.Context, arg CreateShortenLinkParams) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, createShortenLink, arg.ShortCode, arg.OriginalUrl)
	var id interface{}
	err := row.Scan(&id)
	return id, err
}

const incrementViews = `-- name: IncrementViews :exec
UPDATE shorten_links
SET views = views + 1
WHERE short_code = ?
`

func (q *Queries) IncrementViews(ctx context.Context, shortCode string) error {
	_, err := q.db.ExecContext(ctx, incrementViews, shortCode)
	return err
}
